#!/bin/sh

#------------------------------------------------------------
# Define Vars
#------------------------------------------------------------
HASH="k43p01d"


#------------------------------------------------------------
# git checkout
#------------------------------------------------------------
GIT_WORK_TREE=/var/www/virtual/bf/$HASH.bnfy.de git checkout -f


#------------------------------------------------------------
# Datenbankdump einspielen
#------------------------------------------------------------
mysql bf_$HASH </var/www/virtual/bf/$HASH.bnfy.de/db.sql


#------------------------------------------------------------
# .htaccess RewriteBase aktivieren
#------------------------------------------------------------
sed -i 's/#RewriteBase/RewriteBase/g' /var/www/virtual/bf/$HASH.bnfy.de/.htaccess


#------------------------------------------------------------
# Contao: localconfig.php $websitePath anpassen
#------------------------------------------------------------
sed -i 's/\/wiesauplast//g' /var/www/virtual/bf/$HASH.bnfy.de/system/config/localconfig.php


#------------------------------------------------------------
# Verzeichnisschutz hinzufügen
#------------------------------------------------------------
echo -e '\n\nAuthUserFile /var/www/virtual/bf/.htpasswd\nAuthGroupFile /dev/null\nAuthName "Restricted Area"\nAuthType Basic\n<Limit GET>\nrequire valid-user\n</Limit>' >> /var/www/virtual/bf/$HASH.bnfy.de/.htaccess