#!/bin/sh

#--------------------------------------------------------------------------
# Define Vars
#--------------------------------------------------------------------------
projectHash="ProjectName"

virtualPath="/var/www/virtual/user/"
domain="domain.tld"

projectFolderName=$projectHash"."$domain

dbDatabaseSuffix="suffix_"
dbDatabase=$dbDatabaseSuffix$projectHash


#--------------------------------------------------------------------------
# git checkout
#--------------------------------------------------------------------------
GIT_WORK_TREE=$virtualPath$projectFolderName git checkout -f


#--------------------------------------------------------------------------
# Import DB dump
#--------------------------------------------------------------------------
mysql $dbDatabase <$virtualPath$projectFolderName/db.sql


#--------------------------------------------------------------------------
# activate .htaccess RewriteBase
#--------------------------------------------------------------------------
sed -i 's/#RewriteBase/RewriteBase/g' $virtualPath$projectFolderName/.htaccess


#--------------------------------------------------------------------------
# Contao (http://contao.org) specific: change localconfig.php $websitePath
#--------------------------------------------------------------------------
sed -i 's/\/'$projectHash'//g' $virtualPath$projectFolderName/system/config/localconfig.php


#--------------------------------------------------------------------------
# Add a simple dir protection via .htaccess
#--------------------------------------------------------------------------
echo -e '\n\nAuthUserFile '$virtualPath'.htpasswd\nAuthGroupFile /dev/null\nAuthName "Restricted Area"\nAuthType Basic\n<Limit GET>\nrequire valid-user\n</Limit>' >> $virtualPath$projectFolderName/.htaccess