#!/bin/sh

#------------------------------------------------------------
# Define Vars
#------------------------------------------------------------
projectHash=ProjectName

virtualPath=/var/www/virtual/user/
domain=domain.tld

projectPath=$virtualPath${projectHash}.${domain}

dbDatabaseSuffix=suffix_
dbDatabase=$dbDatabaseSuffix$projectHash


#------------------------------------------------------------
# git checkout
#------------------------------------------------------------
GIT_WORK_TREE=$projectPath git checkout -f


#------------------------------------------------------------
# Import DB dump
#------------------------------------------------------------
mysql $dbDatabase < $projectPath/db.sql


#------------------------------------------------------------
# activate .htaccess RewriteBase
#------------------------------------------------------------
sed -i 's/#RewriteBase/RewriteBase/g' $projectPath/.htaccess


#------------------------------------------------------------
# Contao specific: adjust localconfig.php $websitePath
#------------------------------------------------------------
sed -i 's/\/'$projectHash'//g' ${projectPath}/system/config/localconfig.php


#------------------------------------------------------------
# add simple dir protection via .htaccess
#------------------------------------------------------------
echo -e '\n\nAuthUserFile '${virtualPath}'.htpasswd\nAuthGroupFile /dev/null\nAuthName "Restricted Area"\nAuthType Basic\n<Limit GET>\nrequire valid-user\n</Limit>' >> ${projectPath}/.htaccess