#!/bin/sh

#------------------------------------------------------------
# Define Vars
#------------------------------------------------------------
projectHash="ProjectName"

virtualPath="/var/www/virtual/user/"
domain="domain.tld"

projectFolderName=$projectHash"."$domain

dbDatabaseSuffix="suffix_"
dbDatabase=$dbDatabaseSuffix$projectHash


#------------------------------------------------------------
# git checkout
#------------------------------------------------------------
GIT_WORK_TREE=$virtualPath$projectFolderName git checkout -f


#------------------------------------------------------------
# Datenbankdump einspielen
#------------------------------------------------------------
mysql $dbDatabase <$virtualPath$projectFolderName/db.sql


#------------------------------------------------------------
# .htaccess RewriteBase aktivieren
#------------------------------------------------------------
sed -i 's/#RewriteBase/RewriteBase/g' $virtualPath$projectFolderName/.htaccess


#------------------------------------------------------------
# Contao: localconfig.php $websitePath anpassen
#------------------------------------------------------------
sed -i 's/\/'$projectHash'//g' $virtualPath$projectFolderName/system/config/localconfig.php


#------------------------------------------------------------
# Verzeichnisschutz hinzufügen
#------------------------------------------------------------
echo -e '\n\nAuthUserFile '$virtualPath'.htpasswd\nAuthGroupFile /dev/null\nAuthName "Restricted Area"\nAuthType Basic\n<Limit GET>\nrequire valid-user\n</Limit>' >> $virtualPath$projectFolderName/.htaccess