#!/bin/sh

#------------------------------------------------------------
# Define Vars
#------------------------------------------------------------
projectHash="ProjectName"

mysqldumpPath="/Applications/MAMP/Library/bin/"
projectPath="~/Sites/htdocs/"$projectHash"/"

dbUser="root"
dbPass="root"
dbDatabaseSuffix="suffix_"
dbDatabase=$dbDatabaseSuffix$projectHash


#------------------------------------------------------------
# export mySQL-Dump
#------------------------------------------------------------
$mysqldumpPathmysqldump -u $dbUser -p$dbPass $dbDatabase > $projectPathdb.sql

# Exit success
exit 0