#!/bin/sh

#------------------------------------------------------------
# Define Vars
#------------------------------------------------------------
projectHash="ProjectName"

mysqldumpPath="/Applications/MAMP/Library/bin/"
projectPath="~/Sites/htdocs/"${projectHash}

dbUser="root"
dbPass="root"
dbDatabaseSuffix="suffix_"
dbDatabase=${dbDatabaseSuffix}${projectHash}


#------------------------------------------------------------
# mySQL-Dump exportieren
#------------------------------------------------------------
${mysqldumpPath}mysqldump -u $dbUser -p$dbPass $dbDatabase > ${projectPath}db.sql
exit 0